@startuml
class users {
	
}

class projects{
	
}


class customers{
	id
	__ Properties __
	name
	phone
	birthday
}

class inventory_items {
	id
	inventory_category_id
	__ Properties __
	number
	manufacturer
	description
	value
	status
}


class inventory_warehouses {
	id
	__ Properties __
	name
	location
}


class inventory_categories{
    id
    __ Properties __
    name
    description
}


class inventory_providers{
	id
	__ Properties __
	name
	address0
	address1
	city
	state
	country
	phone0
	phone1
	fax
	business
	email
	contact0
	contact1
}


class inventory_movements{
	id
	user_id
	project_id
	inventory_item_id
	.. Direction ..
	inventory_provider_id
	user_from_id
	user_to_id
	warehouse_to_id
	warehouse_from_id
	__ Properties __
	serial_number
	quantity
	document
	document_type
	value
	other_destiny
	date
}

inventory_items --> "belong to 1" inventory_categories

inventory_movements --> "by" users
inventory_movements --> "of" projects
inventory_movements --> "of" inventory_items
inventory_movements -> "from\nto" inventory_providers
inventory_movements -> "from\nto" inventory_warehouses
inventory_movements -> "from\nto" customers
inventory_movements -> "from\nto" users
@enduml